verbosity level in command line & replace prints by loggings
BlueBrain/EModelRunner pull request #50
Opened 2022-04-25 10:57 UTC by AurelienJaquier

2022-04-25 11:46 UTC, anilbey approved these changes
Great work!
I just added one small comment.

2022-04-25 11:46 UTC, anilbey commented on emodelrunner/parsing_utilities.py
> +        verbosity (int): verbosity level. 0 for warning, 1 fro info and 2 or more for debug
small typo `fro -> for`

2022-04-25 11:48 UTC, anilbey requested changes
Can you just add 2 unit tests one for `get_parser_args` and the other for `set_verbosity` to test them?

2022-04-25 11:49 UTC, AurelienJaquier commented on emodelrunner/parsing_utilities.py
> +        verbosity (int): verbosity level. 0 for warning, 1 fro info and 2 or more for debug
done in next commit

2022-04-25 14:07 UTC, AurelienJaquier commented
Unfortunately, I couldn't test the logging level, since pytest overwrites it with its own. So I am only adding a test for the argument parsing function.

2022-04-25 15:25 UTC, anilbey commented
Ok good, for this scenario there is a very cool built-in of Python that gives us ability to replace the module with a mock object and make sure that object is called the correct way.
 https://docs.python.org/3/library/unittest.mock.html
Let me show one example on this PR.

2022-04-26 06:38 UTC, AurelienJaquier commented
Great, thank you very much, the new test looks very nice. It's ok to merge on my side. What do you think ?

2022-04-26 07:39 UTC, anilbey approved these changes
Also good for me, go ahead :)

2022-04-26 08:06 UTC, merged